name = "tiktok-live-presenter-worker"
main = "worker.js"
compatibility_date = "2025-10-16"

[env.production]
name = "tiktok-live-presenter-worker-prod"

[vars]
# removed telegram secrets


# To bind secrets use: wrangler secret put BOT_TOKEN
# and wrangler secret put CHAT_ID

[[routes]]
pattern = "jobs.whitebedding.net/tiktok_live_presenter/api/submit"
zone_id = "474890266a9fde455ac23cfd946f7c49"